### ISSUE TITLE
`unwrap_none_or_else()`

### ISSUE THREAD

**Issue by dcormier** [Demindiro/unwrap_none#2]
Would you be open to a contribution adding an `unwrap_none_or_else()` function? It would be just like `unwrap_or_else()` except for `None`.

**Comment by Demindiro** [comment]
I don't think having `unwrap_none_or_else()` would make much sense, since it will always have to return `()`, like `unwrap_none()`.

**Comment by dcormier** [comment]
I was thinking it would be useful when you have code that you'd like to execute only if `None`. Even if you just want to format a panic message. Along the lines of `.unwrap_or_else(|| panic(&format!("contextual message about {}", thing)))` (using `.expect(&format!(...))` will rightfully make clippy yell at you).

**Comment by Demindiro** [comment]
> Even if you just want to format a panic message. Along the lines of `.unwrap_or_else(|| panic(&format!("contextual message about {}", thing)))`

I think that's a fair usecase. A PR would be welcome.
